server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ministerio
    username: root
    password: app_employees
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
